### PR TITLE
fix: writer permission check

### LINKED ISSUE #424: Writer permission is incorrectly validated during the merge
The permission check should validate against the ACL state for the corresponding vertex hash

https://github.com/topology-foundation/ts-drp/blob/9b423533b2dddfd9200d30f8bf41816084ee4325/packages/object/src/index.ts#L235-L245

https://github.com/topology-foundation/ts-drp/blob/9b423533b2dddfd9200d30f8bf41816084ee4325/packages/object/src/index.ts#L318-L323

Previously this was done correctly, however due to several code rebases it became incorrect.

https://github.com/topology-foundation/ts-drp/blob/cc45067aec53f4148945c04a532ef6647ea21bdd/packages/object/src/index.ts#L185-L195

### PR DESCRIPTION
**Pull request by winprn**
resolves #424

### CODE REVIEW

File: packages/object/src/index.ts [hunk 1]
```diff
@@ -247,7 +247,8 @@ export class DRPObject implements ObjectPb.DRPObjectBase {
 			}
 
 			try {
-				if (!this._checkWriterPermission(vertex.peerId)) {
+				const acl = this._computeObjectACL(vertex.dependencies);
+				if (!(this.acl as ACL).permissionless && !acl.query_isWriter(vertex.peerId)) {
```
Comment (magnified103) [inline packages/object/src/index.ts:251]: Should it be `!acl.permissionless`?

Comment (winprn) [reply packages/object/src/index.ts:251]: resolved

File: packages/object/src/index.ts [hunk 2]
```diff
@@ -247,7 +247,8 @@ export class DRPObject implements ObjectPb.DRPObjectBase {
 			}
 
 			try {
-				if (!this._checkWriterPermission(vertex.peerId)) {
+				const acl = this._computeObjectACL(vertex.dependencies);
+				if (!(acl as ACL).permissionless && !acl.query_isWriter(vertex.peerId)) {
```
Comment (hoangquocvietuet) [inline packages/object/src/index.ts:251]: Why don't we update `_checkWriterPermission` instead?

File: packages/object/tests/hashgraph.test.ts [hunk 3]
```diff
@@ -3,7 +3,16 @@ import { SetDRP } from "@ts-drp/blueprints/src/Set/index.js";
 import { beforeAll, beforeEach, describe, expect, test } from "vitest";
 
 import { ObjectACL } from "../src/acl/index.js";
-import { ACLGroup, DRPObject, DrpType, Hash, HashGraph, type Operation } from "../src/index.js";
+import {
+	ACLGroup,
+	computeHash,
```
Comment (d-roak) [inline packages/object/tests/hashgraph.test.ts:8]: use the `newVertex` stuff, you need to merge main
